const CFG=window.ATLAS_CONFIG;
const db=window.supabase.createClient(CFG.SUPABASE_URL,CFG.SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let REGIONS=[];let S={user:null,country:null,countries:[],armies:[],selected:null,layer:'political',active:'command',authMode:'login',busy:false};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const full=n=>Number(n||0).toLocaleString();
const getR=id=>REGIONS.find(r=>r.id===id);
const owner=id=>S.countries.find(c=>(c.region_ids||[]).includes(id));
function toast(m,err=false){const x=$('toast');if(!x)return;x.textContent=m;x.className='toast show'+(err?' err':'');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.className='toast',3000)}
function show(screen){['auth','found','game'].forEach(id=>$(id)?.classList.toggle('hidden',id!==screen));}
async function loadRegions(){const {data,error}=await db.from('regions').select('*').order('id');if(error)throw error;REGIONS=data||[]}
async function loadWorld(){if(!S.user){S.countries=[];return}const {data,error}=await db.from('countries').select('*');if(error)throw error;S.countries=data||[]}
async function loadMe(){if(!S.user){S.country=null;return}const {data,error}=await db.from('countries').select('*').eq('user_id',S.user.id).maybeSingle();if(error)throw error;S.country=data||null}
async function api(endpoint,action,payload={}){const {data:{session}}=await db.auth.getSession();if(!session)throw Error('Please log in first.');const res=await fetch(`${CFG.SUPABASE_URL}/functions/v1/${endpoint}`,{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,apikey:CFG.SUPABASE_PUBLISHABLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});let body={};try{body=await res.json()}catch{}if(!res.ok)throw Error(body.error||'Server action failed');return body}
async function game(action,payload={}){return api('game-actions',action,payload)}
async function strategy(action,payload={}){return api('strategy-actions',action,payload)}
function terrainIcon(t){return ({Plains:'▦',Forest:'♣',Mountains:'⌃',Desert:'◌','River Valley':'≈',Highlands:'⌂',Coast:'≋',Tundra:'❄',Wetlands:'≈',Steppe:'◇'})[t]||'•'}
function countryColor(id){let h=0;for(const ch of String(id))h=(h*31+ch.charCodeAt(0))%360;return `hsl(${h} 44% 42%)`}
function mapSvg(){let h=`<svg id="worldSvg" viewBox="0 0 1200 720" role="img" aria-label="Atlas Realms strategic map"><defs><linearGradient id="sea" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#18354a"/><stop offset="1" stop-color="#07151f"/></linearGradient><filter id="shadow"><feDropShadow dx="0" dy="4" stdDeviation="4" flood-opacity=".28"/></filter></defs><rect width="1200" height="720" fill="url(#sea)"/>`;
for(const r of REGIONS){const o=owner(r.id);const pts=(r.polygon||[]).map(p=>p.join(',')).join(' ');let fill=o?countryColor(o.id):'#3a5362';if(S.layer==='terrain')fill=({Plains:'#647f50',Forest:'#3f684a',Mountains:'#6f777e',Desert:'#9a774f','River Valley':'#487777',Highlands:'#68755e',Coast:'#46788b',Tundra:'#83929b',Wetlands:'#527664',Steppe:'#807950'})[r.terrain]||fill;if(S.layer==='population'){const n=Math.log10(Math.max(1,r.base_population||1));fill=`hsl(${190-Math.min(120,n*18)} 48% 43%)`}if(S.layer==='resources'){const n=Object.values(r.resources||{}).reduce((a,b)=>a+Number(b||0),0);fill=`hsl(${185-Math.min(130,n*2)} 50% 42%)`}if(S.layer==='military'){const m=o?Number(o.military||0):0;fill=m>220?'#8d4f4f':m>100?'#765c4b':'#334d5c'}const selected=S.selected===r.id;h+=`<polygon class="province ${selected?'selected':''} ${o?'owned':''}" data-rid="${esc(r.id)}" points="${pts}" fill="${fill}" filter="url(#shadow)"></polygon><text x="${r.center_x}" y="${r.center_y}" text-anchor="middle" class="province-label">${esc(r.name)}</text>`;if((r.city_count||0)>0)h+=`<circle cx="${r.center_x}" cy="${r.center_y-12}" r="3" class="city"></circle>`}
h+=`<path d="M75 570 C180 510 280 590 390 525 S620 450 760 520 S960 470 1130 555" class="river"></path><path d="M110 620 L1090 620" class="road"></path></svg>`;return h}
function renderMap(target){const el=$(target);if(!el)return;el.innerHTML=`<div class="map-toolbar"><input id="mapSearch" placeholder="Search provinces…"><div class="layer-tabs">${['political','terrain','resources','population','military'].map(x=>`<button class="layer ${S.layer===x?'active':''}" data-layer="${x}">${x}</button>`).join('')}</div></div><div class="map-canvas"><div class="map-watermark">ATLAS REALMS</div>${mapSvg()}<div class="map-hud"><button class="btn" id="zoomPlus">+</button><span id="zoomPct">100%</span><button class="btn" id="zoomMinus">−</button><button class="btn" id="zoomReset">↺</button></div><div class="map-legend"><span>● City</span><span>≈ River</span><span>┄ Route</span><span>Click a province</span></div></div>`;
let svg=el.querySelector('#worldSvg'),canvas=el.querySelector('.map-canvas'),scale=1,tx=0,ty=0,drag=false,sx=0,sy=0,ox=0,oy=0;const apply=()=>{svg.style.transform=`translate(${tx}px,${ty}px) scale(${scale})`;el.querySelector('#zoomPct').textContent=`${Math.round(scale*100)}%`};el.querySelector('#zoomPlus').onclick=()=>{scale=Math.min(2.5,scale+.12);apply()};el.querySelector('#zoomMinus').onclick=()=>{scale=Math.max(.8,scale-.12);apply()};el.querySelector('#zoomReset').onclick=()=>{scale=1;tx=ty=0;apply()};canvas.addEventListener('pointerdown',e=>{if(e.target.closest('.province'))return;drag=true;sx=e.clientX;sy=e.clientY;ox=tx;oy=ty;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;tx=ox+e.clientX-sx;ty=oy+e.clientY-sy;apply()});canvas.addEventListener('pointerup',()=>drag=false);canvas.addEventListener('pointercancel',()=>drag=false);canvas.addEventListener('wheel',e=>{if(!e.ctrlKey)return;e.preventDefault();scale=Math.max(.8,Math.min(2.5,scale+(e.deltaY<0?.08:-.08)));apply()},{passive:false});el.querySelectorAll('.province').forEach(p=>p.onclick=e=>{e.stopPropagation();selectProvince(p.dataset.rid)});el.querySelectorAll('[data-layer]').forEach(b=>b.onclick=()=>{S.layer=b.dataset.layer;renderMap(target)});el.querySelector('#mapSearch')?.addEventListener('input',e=>{const q=e.target.value.toLowerCase();const hit=REGIONS.find(r=>r.name.toLowerCase().includes(q));if(hit)selectProvince(hit.id)});apply()}
function selectProvince(id){S.selected=id;renderGame()}
function updateInspector(){const r=getR(S.selected),box=$('provinceInspector');if(!box||!r)return;const o=owner(r.id),mine=S.country&&(S.country.region_ids||[]).includes(r.id);box.innerHTML=`<div class="inspect-head"><div><div class="eyebrow">PROVINCE</div><h3>${esc(r.name)}</h3><p>${terrainIcon(r.terrain)} ${esc(r.terrain)} · ${esc(r.climate||'Temperate')}</p></div><span class="flagchip">${o?esc(o.flag_emoji||'🏳️'):'⚑'}</span></div><div class="data-grid"><span>Population<b>${full(r.base_population)}</b></span><span>Area<b>${full(r.land_area_km2)} km²</b></span><span>Food<b>${full(r.resources?.food)}</b></span><span>Iron<b>${full(r.resources?.iron)}</b></span><span>Gold<b>${full(r.resources?.gold)}</b></span><span>Oil<b>${full(r.resources?.oil)}</b></span></div><div class="owner-line">${mine?'Controlled by you':o?`Controlled by ${esc(o.country_name)}`:'Unclaimed'}</div>${S.country&&!mine&&!o&&adjacentToMine(r.id)?`<button class="btn primary wide" id="claimSelected">Claim province · ${full(claimCost())} 🪙</button>`:''}`;box.querySelector('#claimSelected')?.addEventListener('click',claimSelected)}
function adjacentToMine(id){const mine=new Set(S.country?.region_ids||[]);const r=getR(id);return !!r&&[...mine].some(x=>getR(x)?.borders?.includes(id)||r.borders?.includes(x))}
function claimCost(){const n=(S.country?.region_ids||[]).length;return 300+Math.max(0,n-1)*120}
async function claimSelected(){try{const d=await game('claim',{regionId:S.selected});S.country=d.country;await refresh();toast(d.message)}catch(e){toast(e.message,true)}}
function topStats(c){return `<div class="stats-row"><div><span>🪙 Treasury</span><b>${full(c.treasury)}</b></div><div><span>👥 Population</span><b>${full(c.population)}</b></div><div><span>🌾 Food</span><b>${full(c.food)}</b></div><div><span>⚔ Military</span><b>${full(c.military)}</b></div><div><span>⭐ Score</span><b>${full(c.score)}</b></div><div><span>🏳 Provinces</span><b>${(c.region_ids||[]).length}</b></div><div><span>⏱ Turn</span><b>${c.turn_number||1}</b></div></div>`}
function sideNav(){return `<nav class="side-nav">${[['command','Command'],['atlas','Atlas'],['economy','Economy'],['production','Production'],['research','Research'],['diplomacy','Diplomacy'],['military','Military'],['intelligence','Intelligence']].map(([id,label])=>`<button class="side-item ${S.active===id?'active':''}" data-tab="${id}"><span>${({command:'⌘',atlas:'◎',economy:'₿',production:'▣',research:'✦',diplomacy:'⚑',military:'⚔',intelligence:'◉'})[id]}</span>${label}</button>`).join('')}</nav>`}
function commandPanel(c){const r=S.selected?getR(S.selected):null;const neighbors=REGIONS.filter(x=>adjacentToMine(x.id)&&!owner(x.id)).slice(0,5);return `<div class="content-grid"><div class="main-column"><section class="panel command-hero"><div><div class="eyebrow">NATIONAL COMMAND</div><h1>${esc(c.flag_emoji||'🏳️')} ${esc(c.country_name)}</h1><p>${c.last_event?esc(c.last_event):'The world awaits your orders.'}</p></div><button class="btn primary" id="endTurnBtn">End Turn →</button></section><section class="panel"><div class="panel-head"><div><h2>Strategic situation</h2><p>Choose a province, issue orders and expand your sphere.</p></div><span class="live-dot">LIVE WORLD</span></div>${S.selected?`<div class="selected-banner">Selected: <b>${esc(r?.name||S.selected)}</b> · ${r?esc(r.terrain):''}</div>`:''}<div id="mainMap"></div></section></div><aside class="right-column"><section class="panel" id="provinceInspector"><div class="empty"><b>Select a province</b><span>Inspect resources, ownership and expansion options.</span></div></section><section class="panel quick-orders"><div class="panel-head"><h3>Quick Orders</h3></div><div class="quick-grid"><button class="btn" data-tab="production">🏭 Production</button><button class="btn" data-tab="military">⚔ Raise Army</button><button class="btn" data-tab="research">✦ Research</button><button class="btn" data-tab="diplomacy">⚑ Diplomacy</button></div></section><section class="panel"><div class="panel-head"><h3>Frontier</h3></div><div class="mini-list">${neighbors.map(n=>`<button class="intel-row" data-province="${esc(n.id)}"><span>${terrainIcon(n.terrain)} ${esc(n.name)}</span><b>Expand</b></button>`).join('')||'<div class="empty">No open bordering provinces.</div>'}</div></section></aside></div>`}
function economyPanel(c){return `<div class="panel page-panel"><div class="page-head"><div><div class="eyebrow">ECONOMY</div><h1>National economy</h1><p>Turn resources into growth, infrastructure and power.</p></div><div class="hero-number">🪙 ${full(c.treasury)}</div></div><div class="metric-cards">${[['Infrastructure',c.infrastructure],['Education',c.education],['Healthcare',c.healthcare],['Housing',c.housing]].map(([n,v])=>`<div class="metric-card"><span>${n}</span><b>${Math.round(v||0)}/100</b><i><em style="width:${Math.max(0,Math.min(100,Number(v||0)))}%"></em></i></div>`).join('')}</div><h3>National projects</h3><div class="project-grid">${['infrastructure','education','healthcare','housing','farm','mine','market','port','fort'].map(x=>`<button class="project" data-dev="${x}"><span>${({infrastructure:'🏗️',education:'🎓',healthcare:'🏥',housing:'🏠',farm:'🌾',mine:'⛏️',market:'🏪',port:'⚓',fort:'🛡️'})[x]}</span><b>${x.replace('_',' ')}</b><small>Upgrade ${x==='fort'?'fortification':''}</small></button>`).join('')}</div></div>`}
function productionPanel(c){const b=c.buildings||{};return `<div class="panel page-panel"><div class="page-head"><div><div class="eyebrow">PRODUCTION</div><h1>Industrial command</h1><p>Build an economy that can sustain a long campaign.</p></div></div><div class="production-line">${[['farm','🌾','Food'],['mine','⛏️','Iron & Gold'],['market','🏪','Coins'],['port','⚓','Trade']].map(([k,i,n])=>`<div class="prod"><span>${i}</span><b>${n}</b><strong>Lv ${b[k]||0}</strong><button class="btn small" data-dev="${k}">Upgrade</button></div>`).join('')}</div><div class="notice"><b>Infrastructure matters.</b> Production growth compounds with provinces, technology and buildings. Forts also strengthen defensive positions.</div></div>`}
function researchPanel(c){const techs=new Set(c.techs||[]);const items=[['agri','Agricultural Science','Boost food output'],['industry','Industrialization','Boost production'],['admin','State Administration','Improve governance'],['logistics','Logistics Network','Improve military efficiency'],['energy','Energy Systems','Unlock advanced industry']];return `<div class="panel page-panel"><div class="page-head"><div><div class="eyebrow">RESEARCH</div><h1>Technology tree</h1><p>Research in stages to gain lasting strategic advantages.</p></div></div><div class="tech-tree">${items.map(([k,n,d])=>`<div class="tech-node ${techs.has(k)?'done':''}"><div><span class="tech-icon">${techs.has(k)?'✓':'✦'}</span><div><b>${n}</b><small>${d}</small></div></div><button class="btn" data-tech="${k}" ${techs.has(k)?'disabled':''}>${techs.has(k)?'Researched':'Research'}</button></div>`).join('')}</div></div>`}
function diplomacyPanel(c){const others=S.countries.filter(x=>x.id!==c.id).slice(0,12);return `<div class="panel page-panel"><div class="page-head"><div><div class="eyebrow">DIPLOMACY</div><h1>Foreign affairs</h1><p>Watch neighbours, establish leverage and decide who becomes an ally or rival.</p></div><span class="pill">Reputation ${c.reputation||50}</span></div><div class="nation-list">${others.map(o=>{const shared=(o.region_ids||[]).some(x=>(c.region_ids||[]).some(y=>getR(x)?.borders?.includes(y)||getR(y)?.borders?.includes(x)));return `<div class="nation-row"><div class="nation-id"><span class="flag-large">${esc(o.flag_emoji||'🏳️')}</span><div><b>${esc(o.country_name)}</b><small>${shared?'Shared border':'No shared border'} · ${full(o.score)} score</small></div></div><div class="nation-actions"><button class="btn small" data-trade-nation="${o.id}">Open channel</button>${shared?`<button class="btn small danger" data-war="${o.id}">Declare war</button>`:''}</div></div>`}).join('')||'<div class="empty">Other nations will appear here as players join.</div>'}</div></div>`}
function militaryPanel(c){return `<div class="panel page-panel"><div class="page-head"><div><div class="eyebrow">MILITARY</div><h1>Army command</h1><p>Raise forces, move them between bordering provinces and fight for territory.</p></div><span class="pill">Military ${full(c.military)}</span></div><div class="army-create"><select id="raiseType"><option value="field_group">Field Group</option><option value="guard">Guard</option><option value="recon">Recon</option><option value="reserve">Reserve</option></select><select id="raiseRegion">${(c.region_ids||[]).map(id=>`<option value="${esc(id)}">${esc(getR(id)?.name||id)}</option>`).join('')}</select><button class="btn primary" id="raiseArmy">Raise force</button></div><div class="army-list">${S.armies.map(a=>{const r=getR(a.region_id),t=a.status==='moving'?getR(a.target_region_id)?.name:'Stationed';return `<div class="army-card"><div><span class="unit-icon">${a.unit_type==='recon'?'◎':a.unit_type==='guard'?'🛡️':a.unit_type==='reserve'?'◈':'⚔️'}</span><b>${esc(a.unit_type)}</b><small>${esc(r?.name||a.region_id)} · ${a.strength} strength · ${esc(t||'Stationed')}</small></div><div class="army-actions">${a.status==='stationed'?`<select data-move-army="${a.id}">${REGIONS.filter(x=>(r?.borders||[]).includes(x.id)).map(x=>`<option value="${esc(x.id)}">Move to ${esc(x.name)}</option>`).join('')}</select><button class="btn small" data-move="${a.id}">Move</button>`:''}<button class="btn small" data-disband="${a.id}">Disband</button></div></div>`}).join('')||'<div class="empty">No field forces yet. Raise your first unit above.</div>'}</div></div>`}
function intelligencePanel(c){const top=[...S.countries].filter(x=>x.id!==c.id).sort((a,b)=>Number(b.score||0)-Number(a.score||0)).slice(0,10);return `<div class="panel page-panel"><div class="page-head"><div><div class="eyebrow">INTELLIGENCE</div><h1>World intelligence</h1><p>Track the leading nations and inspect strategic pressure around your borders.</p></div></div><div class="intel-table">${top.map((o,i)=>`<div class="intel-row wide-row"><span><b>#${i+1}</b> ${esc(o.flag_emoji||'🏳️')} ${esc(o.country_name)}</span><span>Prov ${((o.region_ids||[]).length)} · Mil ${full(o.military)}</span><strong>${full(o.score)}</strong></div>`).join('')||'<div class="empty">No other nations yet.</div>'}</div></div>`}
function atlasPanel(c){return `<div class="panel page-panel atlas-page"><div class="page-head"><div><div class="eyebrow">WORLD MAP</div><h1>Strategic atlas</h1><p>Political borders, terrain, resources and military pressure.</p></div></div><div id="atlasMap"></div></div>`}
async function renderArmies(){try{const d=await strategy('list_armies');S.armies=d.armies||[];if(d.country)S.country=d.country}catch(e){toast(e.message,true)}}
function tabContent(c){switch(S.active){case 'atlas':return atlasPanel(c);case 'economy':return economyPanel(c);case 'production':return productionPanel(c);case 'research':return researchPanel(c);case 'diplomacy':return diplomacyPanel(c);case 'military':return militaryPanel(c);case 'intelligence':return intelligencePanel(c);default:return commandPanel(c)}}
function renderGame(){if(!S.country){show('found');bindFound();return}show('game');$('turnState').textContent=`TURN ${S.country.turn_number||1}`;$('gameContent').innerHTML=`<div class="game-shell"><header class="game-head"><div class="country-title"><span class="flag-large">${esc(S.country.flag_emoji||'🏳️')}</span><div><b>${esc(S.country.country_name)}</b><small>${esc(getR(S.country.capital_region)?.name||'Capital')} · Governing ${(S.country.region_ids||[]).length} provinces</small></div></div><div class="head-actions"><span class="pill">${S.country.last_event?esc(S.country.last_event):'Online'}</span><button class="btn" id="logoutGame">Log out</button></div></header>${topStats(S.country)}<div class="game-layout">${sideNav()}<main class="main-area"><div id="tabRoot">${tabContent(S.country)}</div></main></div></div>`;bindGame();if(S.active==='command')renderMap('mainMap');if(S.active==='atlas')renderMap('atlasMap');updateInspector()}
function bindGame(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{S.active=b.dataset.tab;renderGame()});$('logoutGame')?.addEventListener('click',()=>db.auth.signOut());$('endTurnBtn')?.addEventListener('click',endTurn);document.querySelectorAll('[data-dev]').forEach(b=>b.onclick=()=>dev(b.dataset.dev));document.querySelectorAll('[data-tech]').forEach(b=>b.onclick=()=>researchTech(b.dataset.tech));document.querySelectorAll('[data-province]').forEach(b=>b.onclick=()=>{S.selected=b.dataset.province;renderGame()});$('raiseArmy')?.addEventListener('click',raiseArmy);document.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>moveArmy(b.dataset.move));document.querySelectorAll('[data-disband]').forEach(b=>b.onclick=()=>disbandArmy(b.dataset.disband));document.querySelectorAll('[data-war]').forEach(b=>b.onclick=()=>declareWar(b.dataset.war));document.querySelectorAll('[data-trade-nation]').forEach(b=>b.onclick=()=>toast('Diplomatic channel opened — use the economy desk for trade proposals.'))}
async function dev(type){if(S.busy)return;S.busy=true;try{const d=await game('nation_action',{type});S.country=d.country;await refresh();toast(d.message)}catch(e){toast(e.message,true)}finally{S.busy=false}}
async function researchTech(tech){if(S.busy)return;S.busy=true;try{const d=await game('research',{tech});S.country=d.country;await refresh();toast(d.message)}catch(e){toast(e.message,true)}finally{S.busy=false}}
async function endTurn(){if(S.busy)return;S.busy=true;const b=$('endTurnBtn');if(b)b.disabled=true;try{const d=await game('end_turn');S.country=d.country;await refresh();toast(d.message)}catch(e){toast(e.message,true)}finally{S.busy=false}}
async function raiseArmy(){const type=$('raiseType')?.value,regionId=$('raiseRegion')?.value;if(!type||!regionId)return;try{const d=await strategy('raise_force',{unitType:type,regionId});S.country=d.country;await renderArmies();renderGame();toast(d.message)}catch(e){toast(e.message,true)}}
async function moveArmy(id){const sel=document.querySelector(`[data-move-army="${CSS.escape(id)}"]`);if(!sel)return;try{const d=await strategy('move_force',{armyId:id,targetRegionId:sel.value});S.country=d.country||S.country;await renderArmies();renderGame();toast(d.message)}catch(e){toast(e.message,true)}}
async function disbandArmy(id){try{const d=await strategy('disband_force',{armyId:id});S.country=d.country;await renderArmies();renderGame();toast(d.message)}catch(e){toast(e.message,true)}}
async function declareWar(targetId){if(!confirm('Declare war on this nation?'))return;try{const d=await game('declare_war',{targetId});S.country=d.country;S.active='military';await refresh();toast(d.message)}catch(e){toast(e.message,true)}}
async function refresh(){await Promise.all([loadWorld(),loadMe()]);if(S.country)await renderArmies();renderGame()}
function bindAuth(){document.querySelectorAll('[data-auth]').forEach(b=>b.onclick=()=>{S.authMode=b.dataset.auth;document.querySelectorAll('[data-auth]').forEach(x=>x.classList.toggle('active',x===b));$('authSubmit').textContent=S.authMode==='login'?'Enter the world':'Create my account'});$('authForm').onsubmit=async e=>{e.preventDefault();const email=$('email').value.trim(),password=$('password').value;const fn=S.authMode==='login'?db.auth.signInWithPassword({email,password}):db.auth.signUp({email,password});const {error}=await fn;if(error){$('authMsg').textContent=error.message;return}$('authMsg').textContent='Check your email if confirmation is required, then continue.'}}
function bindFound(){$('foundBtn').onclick=foundCountry;$('frontierBtn').onclick=()=>{const open=REGIONS.find(r=>!owner(r.id));if(open){S.selected=open.id;renderFound()}};renderFound()}
function renderFound(){const f=$('foundMap');if(!f)return;f.innerHTML=`<div class="map-canvas found-canvas">${mapSvg()}<div class="map-legend"><span>Select an unclaimed province</span></div></div>`;f.querySelectorAll('.province').forEach(p=>p.onclick=()=>{S.selected=p.dataset.rid;renderFound();$('selectedFound').textContent=`Selected: ${getR(S.selected)?.name||S.selected}`});$('selectedFound').textContent=S.selected?`Selected: ${getR(S.selected)?.name||S.selected}`:'Select a province on the map.'}
async function foundCountry(){try{if(!S.selected)throw Error('Select a province first.');const d=await game('found_country',{countryName:$('countryName').value.trim(),flag:$('countryFlag').value.trim()||'🏳️',regionId:S.selected});S.country=d.country;await refresh();toast(d.message)}catch(e){$('foundMsg').textContent=e.message;toast(e.message,true)}}
async function boot(){bindAuth();const {data:{session}}=await db.auth.getSession();S.user=session?.user||null;await loadRegions();if(S.user){await loadMe();await loadWorld();if(S.country){await renderArmies();renderGame()}else{show('found');bindFound()}}else show('auth');db.auth.onAuthStateChange(async(_,session)=>{S.user=session?.user||null;if(S.user){await loadMe();await loadWorld();if(S.country){await renderArmies();renderGame()}else{show('found');bindFound()}}else{S.country=null;show('auth')}})}
boot().catch(e=>{console.error(e);$('authMsg').textContent=e.message;toast(e.message,true)});
